---
title: "MPAs and climate change: regional sea-surface temperature means"
output: html_notebook
author: Mark Ruddy
date: 2017-04-27
---

Task is to find mean temperature values for latitudinal regions of the globe.


Packages
```{r}
library(raster)
library(ncdf4)
library(rgdal)
library(dplyr)
library(tibble)
```


## Raster summary statistics

Read in Marine Protected Areas
```{r}
mpas.in <- read.csv("../nn_extractedA2c.csv", header = TRUE)

mpas.xy <- mpas.in[,2:3]

rm(mpas.in)
```

Read in CMIP5 RCP4.5 max
```{r get-cmip-test}

cmip <- "../trend_yearmax_ensemble_RCP45.nc"
cmip <- raster(cmip) # Read in raster
map.extent <- c(-180, 180, -90, 90) # Reset for layer, orginal orientation was 0-360 longitude
extent(cmip) <- map.extent # Change extent

source("../revrotate.R") # Rotate raster layer to align with MPA points
cmip <- revrotate(cmip)
extent(cmip) <- map.extent

rm("map.extent")
```


Read in [Natural Earth](http://www.naturalearthdata.com/) 1:110m world vector, then convert to simple raster.

```{r get-land-test}

# Natural Earth 110m data. Comes as zip file 
url <- "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_land.zip" # web location

localDir <- "../data"

if (!file.exists(localDir)) {
  dir.create(localDir)
}

dwnld <- paste(localDir, basename(url), sep = "/") # zip file destination

if (!file.exists(dwnld)) {
  download.file(url = url, destfile = dwnld, method = "auto") # download from web
  unzip(dwnld, exdir = localDir) # unzip
}

land <- readOGR(dsn = localDir) # Read in shapefile using `rgdal`. No need to specify shapefile name as there's only one in the directory we created above.

rm(url, localDir, dwnld) # clean up workspace
```


```{r cmip-sst-only}
## Mask CMIP5 with land surface ##
# "cmip" is CMIP5 netCDF read in by raster
# "land" is vector polygon land surface dataset
cmip.mask <- mask(x = cmip, mask = land, inverse = TRUE)

## Get MPA cells ##
# "mpas.xy" are the MPA longitude and latitude coordinate data
mpas <- SpatialPoints(mpas.xy) # Make MPAs into SpatialPoints class

mpa.cells <- mask(x = cmip, mask = mpas)

## Merge land masked CMIP5 and MPA cells ##
cmip.sst <- merge(cmip.mask, mpa.cells)

rm(cmip.mask)
```

Find mean temperatures
```{r}
# Data.frame for outputs
zones <- c("global", "tropical", "sub-tropical", "temperate", "polar")
zone.means <- data_frame(
  zone = zones, mean_value = NA
)

# Find global means

# Find regional means
# Latitudinal zone extents
## Longitudinal limits
long.lims <- c(-180, 180) 
## Tropical
trop.ext <- extent(c(long.lims, -23.5, 23.5)) 
## Sub-tropical
nsubtrop.ext <- extent(c(long.lims, 23.5, 40))
ssubtrop.ext <- extent(c(long.lims, -40, -23.5))
## Temperate
ntemp.ext <- extent(c(long.lims, 40, 66.5))
stemp.ext <- extent(c(long.lims, -66.5, -40))
## Polar
npol.ext <- extent(c(long.lims, 66.5, 90))
spol.ext <- extent(c(long.lims, -90, -66.5))

# Mean raster values
## Global
zone.means[which(zone.means$zone=="global"),2] <- cellStats(cmip.sst, stat = "mean", na.rm = TRUE)

## Tropical
zone.means[which(zone.means$zone=="tropical"),2] <- extract(cmip.sst, trop.ext, fun = mean, na.rm = TRUE)

## Other
## Via function to get total means from raster combined, independent raster extents
source("../functions/extent.means.R")
zone.means[which(zone.means$zone=="polar"),2] <- extent.means(cmip.sst, list(npol.ext, spol.ext))
zone.means[which(zone.means$zone=="sub-tropical"),2] <- extent.means(cmip.sst, list(nsubtrop.ext, ssubtrop.ext))
zone.means[which(zone.means$zone=="temperate"),2] <- extent.means(cmip.sst, list(ntemp.ext, stemp.ext))

rm(list = ls(pattern = ".*ext$|.*lims$"))

zone.means <- zone.means %>% mutate(mean_value = signif(mean_value, 2))

View(zone.means)
```
